// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "autogeneratingdoc",
    "version": "1"
  },
  "schemes": [
    "https"
  ],
  "paths": {
    "/hello": {
      "post": {
        "summary": "hello",
        "description": "",
        "operationId": "hello",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {}
};